### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mungiud** [hrevert/HtProfileImage#1]
pls tell me when you finish this class.
ImageUpload.php have some error i think this error appear only when you not choose in option a resizer..
$resizer = new $resizingOptions['name'];
$resizer->setOptions($resizingOptions['options']);

**Comment by ojhaujjwal** [comment]
Will you dig deeper about your issue?
What is the error message?
What options have you used?
Did you installed this module via composer?

**Comment by ojhaujjwal** [comment]
Okay, I understand the error now.
Hang tight, it will get solved quickly
