### ISSUE TITLE
invoke error in helper page

### ISSUE THREAD

**Issue by stijnhau** [hrevert/HtProfileImage#11]
Strict standards: Declaration of HtProfileImage\View\Helper\ProfileImage::__invoke() should be compatible with Zend\View\Helper\Gravatar::__invoke($email = '', $options = Array, $attribs = Array) in D:\Dropbox\server\Workspace\True-Life\vendor\hrevert\ht-profile-image\src\HtProfileImage\View\Helper\ProfileImage.php on line 19

But it looks like the page is working
Got in the user/index page after a sucesful login.
(also can't upload images but need to verify that more =to anaylse the exact issue

**Comment by ojhaujjwal** [comment]
@stijnhau It works on my machine. But, I will take care of it. I have extended `Zend\View\Helper\Gravatar`. Dont`t worry I will find a way fast!

**Comment by stijnhau** [comment]
im using the dev-master version and using zf 2.3.2 (dev) but had it also in 2.3.0

**Comment by ojhaujjwal** [comment]
That's probably due to PHP version! what's the PHP version of yours?

**Comment by stijnhau** [comment]
currently for development im on 5.4.12 (wamp server on windows 8.11)

**Comment by ojhaujjwal** [comment]
I deleted the tag `2.0.1`. There are a lot of issues. I will fix those issues and tag again!

**Comment by stijnhau** [comment]
Any idea about the time needed?

**Comment by ojhaujjwal** [comment]
I will try to fix these issues within today!

**Comment by ojhaujjwal** [comment]
@stijnhau I need someone to help me out in tests!

**Comment by stijnhau** [comment]
Oke.
do you have skype / or some simular client to chat?

**Comment by ojhaujjwal** [comment]
http://facebook.com/ojhaujjwal

**Comment by ojhaujjwal** [comment]
Fixed in 2851a5c0612e1fbbf82a8a92b98538af37a56cd3 and 70b3094b58143d99577eb301f08600d3a031c1cb
