### ISSUE TITLE
Image delete feature request

### ISSUE THREAD

**Issue by stijnhau** [hrevert/HtProfileImage#19]
Maybe it is a nice feature to have an option to go back to the gravatar image bui the gui.
So doing a delete of the file in the data dir.

**Comment by ojhaujjwal** [comment]
You mean deleting an image?

**Comment by stijnhau** [comment]
Yes

**Comment by ojhaujjwal** [comment]
Create your own controller action for that!

``` php
$imagePath = $this->getServiceLocator()->get('HtProfileImage\StorageModel')->getUserImage($user);
unlink($path); // deleted
```

**Comment by stijnhau** [comment]
i think it should be added to module.
Also i don't have time today so i created an issue in case someone olse want's to do it or so i don't forget to create a PR.

**Comment by ojhaujjwal** [comment]
Hey try using branch, `feature/image-delete` or if you use composer, `dev-feature/image-delete`,
Access the url, `http://your-app/user/delete-image/[:userId]`!
If that works, I will merge it to master  branch!

**Comment by stijnhau** [comment]
Oke i will testthat version but it will be in the weekend

**Comment by ojhaujjwal** [comment]
@stijnhau Hey that will take 10 mins at max!

**Comment by stijnhau** [comment]
@ojhaujjwal 
probably yes.
But at the moment i don't have acces to that project and later on the day i don't have time.
So just to be safe i say weekend becausde i don't know what will happen the rest of the week.

Maybe also add that delete link to the view? maybe only when wanted by a seeting in the global file?

**Comment by stijnhau** [comment]
Oke tested it and at first i got an error because i didn't enable in the options file
so please add it to the option (global) fille also.
Second the remarks i made earllier this week.

If those are fixed i think it can be merged.

**Comment by stijnhau** [comment]
a

**Comment by stijnhau** [comment]
when it wasn't enabled because it could use that not extsiting action you wanted to use.

**Comment by ojhaujjwal** [comment]
@stijnhau Are you sure that you got an error when it is not enabled? If yes, can you please provide some more details on the error.

**Comment by stijnhau** [comment]
Some error that the requested controller had no action for that.
Maybe was BjyAuthorize blocking something it shouldn't.
Wanted to retest it today but didn't have time (tommorow won't be bettter)
will do some more test when i have time.

**Comment by ojhaujjwal** [comment]
I think you have some time now.
If yes, can you please provide some more details on the last error.

**Comment by stijnhau** [comment]
My mistake.
I thought that the not found template was a nice warning message and not the error like in zf2(disbaled a module of me that overwrote that.)
So if you could just ad those link top the view and the option to enable and diables to the global file than it's perfect.

**Comment by ojhaujjwal** [comment]
I have added options to global.php file.
But, I won`t add the link to the template. This module is just a staring point. Just override the view templates.

**Comment by stijnhau** [comment]
Indeed it's a starting point an not a sane person would overwrite the view, because it isn't nice looking and what we want.
So my idea is to add the delete link depending if de option is enabled or disabled so that we can simply see what is the delete link without having to look in code.

**Comment by ojhaujjwal** [comment]
Send a PR.
