### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mungiud** [hrevert/HtProfileImage#2]
tank you for prompt reponse but error still there , i resolve for myself, but now i put your code back and the error still exists.
the applicaiton don't enter in this condition
if (is_object($resizingOptions) && $resizingOptions instanceof ResizingInterface) {
                    $resizer = $resizingOptions;
                }
\Note: i extend your class because i use custom entity for sfcuser.
Tell me if you want to stop bugging with this errors because i can easily modyfy for myself the code.
Fatal error: Cannot use object of type HCommons\Image\AdaptiveResizing as array in C:\wamp\www\module\Application\src\Application\Service\ImageUpload.php on line 39

**Comment by ojhaujjwal** [comment]
Are you sure? Did you re downloaded via composer?
If you can solve the error, send a pull request!
We will be happy to accept.

**Comment by ojhaujjwal** [comment]
I suggest to use "dev-master" version till the issue is not fixed.

**Comment by mungiud** [comment]
yes i m sure i m not use composer for your class because it require WebinoImageThumb i think and this say that can't found so i make a zip copy and replaced manually. i am sure because this $resizingOptions instanceof ResizingInterface is false so don't enter in that condition how i say. i don't know how to use github to make a pull and request in general because i worked alone at the companies i don't know how to use exactly this kind of team tool but i think when you have time to solve problem yourself because you think this code.
if (is_object($resizingOptions) && $resizingOptions instanceof ResizingInterface) {
                    $resizer = $resizingOptions;
                } else {
                    $resizer = new $resizingOptions;
                    //$resizer->setOptions($resizingOptions['options']);
                }
this is the only change a i make to quick fix for what i want.

**Comment by ojhaujjwal** [comment]
Please use composer to install otherwise this module wont work. Its the best Php dependancy manager available on the planet. Follow this link http://getcomposer.org/doc/. Then, install this module and create another issue.

**Comment by mungiud** [comment]
I use composer ofcorse but for some packages some with depency or some not found i copy mannualy. and module and with that little change the module works well without install from composer. i spend to many time to make this work because last phpthumb was recently updated to 2.0 and is PSR-0 compliant  and missing some error classes and for this changed WebinoImageThumb had i made some changes. when i try to install by compser dev-amster says: hrevert/... requires webino/webino-image/thumb dev-mastere -> no matching package found

**Comment by ojhaujjwal** [comment]
If that error appears in installation, then, add `"webino/webino-image/thumb": "dev-master"` to your composer and update and then add `"hrevert/ht-profile-image": "dev-master"`   to composer to update

**Comment by mungiud** [comment]
i try already this and still don't install dont find webino class automatically

**Comment by ojhaujjwal** [comment]
Try adding `"webino/webino-image-thumb": "dev-master",` && `"hrevert/ht-profile-image": "dev-master",` to your composer.json and run `php composer.phar update`

**Comment by ojhaujjwal** [comment]
I have updated the installation method

**Comment by mungiud** [comment]
i will try tonight

**Comment by ojhaujjwal** [comment]
@mungiud Did you try? If not installed, please open new issue with heading, `"Could not Install'` or whatever you like.

**Comment by mungiud** [comment]
i succes instaled like this:
"webino/webino-image-thumb": "dev-master",
"hrevert/ht-profile-image": "1.0._",
"ujjwal/h-commons": "1.3._"

one of this install phpthumb

after this receive:

Catchable fatal error: Argument 3 passed to PHPThumb\GD::__construct() must be an instance of PHPThumb\PluginCollection, array given, called in C:\wamp\www\vendor\webino\webino-image-thumb\src\WebinoImageThumb\WebinoImageThumb.php on line 35 and defined in C:\wamp\www\vendor\dannytrue\phpthumb\src\PHPThumb\GD.php on line 96

after o modified and get rid of this error i upload an image

```
C:\wamp\www\vendor\dannytrue\phpthumb\src\PHPThumb\GD.php:277
```

Message:

```
$width and $height must be numeric and greater than zero
```

Stack trace:

```
#0 C:\wamp\www\vendor\ujjwal\h-commons\src\HCommons\Image\AdaptiveResizing.php(11): PHPThumb\GD->adaptiveResize(NULL, NULL)
#1 C:\wamp\www\vendor\ujjwal\h-commons\src\HCommons\Image\AbstractResizing.php(42): HCommons\Image\AdaptiveResizing->manipulate(Object(PHPThumb\GD))
#2 C:\wamp\www\module\Application\src\Application\Service\ImageUpload.php(43): HCommons\Image\AbstractResizing->getPhpThumb()
#3 C:\wamp\www\vendor\hrevert\ht-profile-image\src\HtProfileImage\Controller\HtProfileImageController.php(25): Application\Service\ImageUpload->uploadImage(Object(Application\Entity\User), Object(HtProfileImage\Form\ProfileImageForm), Array)
#4 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(83): HtProfileImage\Controller\HtProfileImageController->profileAction()
```

I don't know if it because your  class but i think is because that changes happend lately in phpthumb, i set in your config the image size if you ask.

**Comment by mungiud** [comment]
oh sorry i forgot to update code for my application service image upload who rewrite your service. Now everything goes ok with default setting. So tank tou for your module. I will must change a little bit because i want to take gender for another table (a user details table on-to-one) but how i say your module in fine.

**Comment by ojhaujjwal** [comment]
You better not update the code for upgrading in near future.

**Comment by mungiud** [comment]
i don't understood, what to not upgrade

**Comment by ojhaujjwal** [comment]
You should not edit the code of this module. Doing so, you can upgrade the module in near future. I think you should not use another table, `user_details` or whatever for gender.

**Comment by mungiud** [comment]
i not modified your module i just extend your classes. my application require this. i have a table barebo0ne with user and 2-3 kind of other users who don't have similar proprietes. i want that zfcuser table to remain untouched. for example bjyauthorize uses other tables for take the user type.
